from django.urls import path
from . import views
urlpatterns = [
    path('login', views.UserLoginAPIView.as_view(), name='login'),
    path('logout', views.UserLogoutAPIView.as_view(), name='logout'),
    path('manufacturers',views.ManufacturerListCreateAPIView.as_view(), name='manufacturer-list'),
    path('cities',views.CityListCreateAPIView.as_view(), name='city-list'),
    path('cities/<uuid:pk>',views.CityRetrieveUpdateDestroyAPIView.as_view(), name='city-detail'),
    path('manufacturers/<uuid:pk>',views.ManufacturerRetrieveUpdateDestroyAPIView.as_view(), name='manufacturer-detail'),
    path('locations',views.LocationListCreateAPIView.as_view(), name='location-list'),
    path('locations/<uuid:pk>',views.LocationRetrieveUpdateDestroyAPIView.as_view(), name='location-detail'),
    path('vehicles',views.VehicleListCreateAPIView.as_view(), name='vehicle-list'),
    path('vehicles/<uuid:pk>',views.VehicleRetrieveUpdateDestroyAPIView.as_view(), name='vehicle-detail'),
    path('users/activation', views.AccountActivationAPIView.as_view(), name='user-activation'),
    path('users/<uuid:pk>/status',views.UserChangeStatusAPIView.as_view(), name='user-status'),
    path('users/password-reset', views.ResetPasswordAPIView.as_view(), name='user-reset-password'),
    path('users/password-reset-request', views.ResetPasswordRequestAPIView.as_view(), name='user-reset-password-request'),
    path('users/password-change', views.PasswordChangeAPIView.as_view(), name='user-password-change'),
    path('users', views.UserListCreateAPIView.as_view(), name='user-list'),
    path('users/me', views.UserProfileAPIView.as_view(), name='user-profile'),
    path('users/me/location', views.UserLocationAPIView.as_view(), name='assigned-location'),
    path('users/<uuid:pk>', views.UserRetrieveUpdateDestroyAPIView.as_view(), name='user-detail'),
    path('users/<uuid:pk>/assignment',views.UserAssignmentAPIView.as_view(), name='user-assignment'),
    path('failure-reports',views.FailureReportListCreateAPIView.as_view(), name='failure-report-list'),
    path('failure-reports/<uuid:pk>',views.FailureReportRetrieveAPIView.as_view(), name='failure-report-detail'),
    path('failure-reports/<uuid:pk>/management', views.FailureReportManagementAPIView.as_view(), name='failure-report-management'),
    path('failure-reports/<uuid:pk>/action',views.FailureReportActionAPIView.as_view(), name='failure-report-action'),
    path('repair-reports',views.RepairReportListAPIView.as_view(), name='repair-report-list'),
    path('repair-reports/<uuid:pk>',views.RepairReportRetrieveUpdateAPIView.as_view(), name='repair-report-detail'),
    path('repair-reports/my-workshop', views.RepairReportsInWorkshopListAPIView.as_view(), name='workshop-repair-report-list'),
    path('repair-reports/related-repairs/<uuid:vehicle_id>',views.RelatedVehicleRepairReportsListAPIView.as_view(), name='related-repair-report-list'),
    path('repair-reports/<uuid:pk>/status', views.RepairReportChangeStatusAPIView.as_view(), name='repair-report-status'),
    path('repair-reports/<uuid:pk>/rejections', views.RepairReportRejectAPIView.as_view(), name='repair-report-reject'),
    path('repair-reports/rejections',views.RepairReportRejectionListAPIView.as_view(), name='repair-report-rejection-list'),
    path('repair-reports/rejections/<uuid:pk>',views.RepairReportRejectionRetrieveAPIView.as_view(), name='repair-report-rejection-detail'),
]